spring.application.name=api-gateway
server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].id=bff
spring.cloud.gateway.routes[0].uri=lb://bff-smartlogix
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/bff/**

spring.cloud.gateway.routes[1].id=ms-inventario
spring.cloud.gateway.routes[1].uri=lb://ms-inventario
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/inventario/**

spring.cloud.gateway.routes[2].id=ms-pedidos
spring.cloud.gateway.routes[2].uri=lb://ms-pedidos
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/pedidos/**

spring.cloud.gateway.routes[3].id=ms-envios
spring.cloud.gateway.routes[3].uri=lb://ms-envios
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/envios/**

spring.cloud.gateway.routes[4].id=auth
spring.cloud.gateway.routes[4].uri=lb://bff-smartlogix
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[5].id=ms-calificaciones
spring.cloud.gateway.routes[5].uri=lb://ms-calificaciones
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/calificaciones/**

spring.cloud.gateway.routes[6].id=ms-proveedores
spring.cloud.gateway.routes[6].uri=lb://ms-proveedores
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/proveedores/**

spring.cloud.gateway.routes[7].id=ms-notificaciones
spring.cloud.gateway.routes[7].uri=lb://ms-notificaciones
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/notificaciones/**

spring.cloud.gateway.routes[8].id=ms-cupones
spring.cloud.gateway.routes[8].uri=lb://ms-cupones
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/cupones/**

management.endpoints.web.exposure.include=health,info,metrics,gateway
management.endpoint.health.show-details=always

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000,http://127.0.0.1:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

# Evita error de CORS duplicado cuando Gateway y BFF agregan headers
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
